### ISSUE TITLE
generate arbitrary ADTs and instances

### ISSUE THREAD

**Issue by fommil** [typelevel/shapeless-contrib#25]
~~~(I'm working on this in ensime-server to thoroughly test our s-exp serialisation layer, creating this as an indicator because I might be able to generalise and send a PR)~~~ (never going to happen)

Serialisation libraries could really benefit from tests that generate arbitrary `Product`s made out of some family of containers and possibly other `Product`s. Then integration testing of serialisation, deserialisation and serialisation again would be very beneficial.

**Comment by alexarchambault** [comment]
Note that I did that in https://github.com/alexarchambault/scalacheck-shapeless (needed it for https://github.com/alexarchambault/argonaut-shapeless).

**Comment by fommil** [comment]
Cool!

**Comment by milessabin** [comment]
@fommil is asking for a generator for _types_ (ie. randomly defined sealed families) rather than a generator of values of manually defined types). I think you did the latter rather than the former.

**Comment by fommil** [comment]
Oh bugger.

**Comment by alexarchambault** [comment]
Ah, you're right. I wished I had that too.

**Comment by fommil** [comment]
guess who's about to get their first feature request!

**Comment by fommil** [comment]
oh, actually, best that this move.
