### ISSUE TITLE
Update to latest ScalaCheck

### ISSUE THREAD

**Issue by eallik** [typelevel/shapeless-contrib#27]
I'm getting:

    [warn] There may be incompatibilities among your library dependencies.
    [warn] Here are some of the libraries that were evicted:
    [warn] 	* org.scalacheck:scalacheck_2.11:1.11.3 -> 1.12.1
    [warn] Run 'evicted' to see detailed eviction warnings

with:

    "org.scalacheck" %% "scalacheck" % "1.12.1",
    "org.typelevel" %% "shapeless-scalacheck" % "0.3",

it was working fine with ScalaCheck 1.11.6.

**Comment by alexarchambault** [comment]
Note that https://github.com/alexarchambault/scalacheck-shapeless uses an up-to-date version of scalacheck.
