### ISSUE TITLE
argonaut / shapeless

### ISSUE THREAD

**Issue by alexarchambault** [typelevel/shapeless-contrib#28]
Would you be ok if I submitted the content of https://github.com/alexarchambault/argonaut-shapeless as a sub-project here? shapeless-contrib looks like the perfect fit for it.

**Comment by milessabin** [comment]
I'm not disagreeing, but why not a stand alone project?

I guess there's a danger of shapeless-contrib devolving into a random grab bag of stuff, all useful, but not obviously related. There's no real cost in have multiple finer grained projects at least where the individual projects make sense on their own.

I think  your shapeless/argonaut stuff does make sense on its own. And actually, I think the shapeless/scalacheck stuff would also make sense on its own.

**Comment by alexarchambault** [comment]
Ok then, I'll keep them as separate projects.
